name: Fast-Api

on: [push]

jobs:
  job1: 
    runs-on: ubuntu-latest
    env: 
      PYTHONPATH: .
    steps:
      - uses: actions/checkout@v1
      - name: Set up Python 3.9.13
        uses: actions/setup-python@v1
        with:
          python-version: 3.9.13
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Test with pytest
        run: |
          pip install pytest
          pytest .

  job2:
    needs: job1
    runs-on:  ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-north-1 